const fs = require("node:fs")
const path = require("node:path")
const assert = require("node:assert/strict")

const bar = fs.readFileSync(path.join(__dirname, "..", "Bar.qml"), "utf8")
const menu = fs.readFileSync(path.join(__dirname, "..", "Menu.qml"), "utf8")
const makefile = fs.readFileSync(path.join(__dirname, "..", "Makefile"), "utf8")
const service = fs.readFileSync(path.join(__dirname, "..", "Service.qml"), "utf8")
const wallpaperTone = fs.readFileSync(path.join(__dirname, "..", "WallpaperTone.qml"), "utf8")
const injected = ["omarchyPath", "barWidgetRegistry", "barConfig"]

for (const property of injected) {
  assert.doesNotMatch(
    bar,
    new RegExp(`required\\s+property\\s+[^\\n]+\\s+${property}\\b`),
    `${property} is injected after Loader construction and cannot be required`
  )
}

assert.match(bar, /WlrLayershell\.namespace:\s*"omacrunch-bar"/)
assert.match(bar, /readonly\s+property\s+int\s+barSize:\s*30/)
assert.match(bar, /readonly\s+property\s+int\s+taskSlotWidth:\s*Style\.space\(18\)/)
assert.match(bar, /readonly\s+property\s+int\s+taskIconSize:\s*Style\.space\(13\)/)
assert.ok(bar.includes('text: "\\ue900"'), "bar menu uses the Omarchy logo glyph")
assert.match(bar, /font\.family:\s*"omarchy"/)
assert.match(bar, /workspaceContent\.implicitWidth\s*\+\s*\(root\.workspaceContentPadding\s*\*\s*2\)/)
assert.match(bar, /visible:\s*taskButton\.client\s*&&\s*taskButton\.client\.activated/)
assert.match(bar, /function\s+debugBarGeometry\s*\(\)/)
assert.match(bar, /"omacrunch\.workspace-taskbar"/)
assert.match(bar, /workspace\.toplevels\.values/)
assert.match(bar, /function\s+summonBarWidget\s*\(id\)/)
assert.match(bar, /showPercentage:\s*false/)
assert.match(bar, /format:\s*"HH:mm"/)
assert.match(bar, /target:\s*"omacrunch-bar"/)
assert.match(bar, /statusSlot\.trayExpanded\s*=\s*!statusSlot\.trayExpanded/)
assert.match(bar, /Behavior on animatedTrayWidth/)
assert.match(bar, /RotationAnimation/)
assert.match(bar, /rotation:\s*statusSlot\.trayExpanded\s*\?\s*0\s*:\s*180/)
assert.match(bar, /id:\s*statusContentClip/)
assert.match(bar, /x:\s*statusSlot\.isTray\s*\?\s*-statusSlot\.toggleWidth\s*:\s*0/)
assert.match(bar, /Collapse tray to the right/)
assert.match(bar, /Expand tray to the left/)
assert.match(bar, /function\s+trayVisualState\s*\(\)/)
assert.match(bar, /managePopupOpen\s*=\s*!statusLoader\.item\.managePopupOpen/)
assert.match(menu, /WlrKeyboardFocus\.OnDemand/)
assert.match(menu, /Qt\.ControlModifier\s*\|\s*Qt\.AltModifier\s*\|\s*Qt\.MetaModifier/)
assert.match(makefile, /omarchy-shell shell hide "\$\(PLUGIN_ID\)"/)
assert.match(makefile, /omarchy plugin update "\$\(PLUGIN_ID\)" --yes/)
assert.doesNotMatch(makefile, /install-local:\s*remove-local/)
assert.match(makefile, /menu lifecycle: open -> closed/)
assert.match(makefile, /omarchy-shell omacrunch toneState/)
assert.match(makefile, /omarchy-shell omacrunch-bar state/)
assert.match(makefile, /tray lifecycle: expanded -> collapsed\/right -> expanded\/left/)
assert.match(makefile, /\.arrowRotation == 180/)
assert.match(makefile, /\.arrowRotation == 0/)
assert.match(makefile, /widgetMetrics\[\]/)
assert.match(makefile, /omacrunch\.workspace-taskbar/)
assert.match(makefile, /shell summon omarchy\.clock/)
assert.match(service, /wallpaperAnalyzed:\s*root\.wallpaperAnalyzed/)
assert.match(service, /function\s+toneState\s*\(\):\s*string/)
assert.match(service, /onAnalyzedChanged:\s*root\.wallpaperAnalyzed\s*=\s*analyzed/)
assert.match(service, /sourcePath:\s*monitorFrame\.dragging\s*\?\s*""\s*:\s*root\.currentBackground/)
assert.match(service, /revision:\s*root\.wallpaperRevision/)
assert.match(service, /function\s+toneDebug\s*\(\):\s*string/)
assert.match(makefile, /omarchy-shell omacrunch toneDebug/)
assert.match(makefile, /wallpaper lifecycle: initial -> refreshed/)
assert.match(service, /function\s+refreshTone\s*\(\):\s*string/)
assert.match(service, /component\s+WidgetSurface:\s*Rectangle/)
assert.match(service, /surfaceOpacity:\s*root\.zoneSurfaceOpacity\(toneZone\)/)
assert.match(service, /color:\s*root\.zoneSurfaceColor\(toneZone\)/)
assert.match(service, /style:\s*Text\.Normal/)
assert.match(service, /outlineColorRight:\s*outlineColor/)
assert.doesNotMatch(service, /style:\s*Text\.Outline/)
assert.match(service, /component\s+ContrastRule:/)
assert.doesNotMatch(service, /color:\s*Util\.alpha\(root\.scrimColor/)
assert.match(service, /WidgetSurface\s*\{\s*toneZone:\s*"body"/)
assert.match(service, /onZonesChanged:\s*root\.wallpaperZones\s*=\s*zones/)
assert.match(service, /requiredExtremeOpacity/)
assert.match(wallpaperTone, /import\s+"ToneSample\.js"\s+as\s+ToneSample/)
assert.match(wallpaperTone, /zones\s*=\s*\(\{\}\)/)
assert.match(wallpaperTone, /gridPixels\.length\s*<\s*216/)
assert.match(makefile, /node tests\/tone-sample\.test\.js/)

console.log("contracts: ok")
