const assert = require("node:assert/strict")
const layout = require("../WidgetLayout.js")
let state = layout.defaults()
assert.equal(layout.entry(state, "eDP-1", "monitor").enabled, true)
assert.equal(layout.entry(state, "eDP-1", "weather").enabled, false)
state = layout.change(state, "eDP-1", "weather", { enabled: true, x: 0.8, y: 0.2 })
assert.equal(layout.entry(state, "HDMI-1", "weather").enabled, false)
const saved = layout.normalize(JSON.parse(JSON.stringify(state)))
assert.deepEqual(saved, state, "layout survives disk roundtrip")
const draft = layout.change(saved, "eDP-1", "weather", { x: 0.1 })
assert.equal(saved.screens["eDP-1"].weather.x, 0.8, "editing does not mutate saved layout")
assert.equal(draft.screens["eDP-1"].weather.x, 0.1)
assert.deepEqual(layout.normalize({version: 99}), layout.defaults())
const corrupt = layout.normalize({version: 1, screens: { "eDP-1": {disk: {enabled: true, x: NaN, y: Infinity}}}})
assert.equal(corrupt.screens["eDP-1"].disk.x, undefined)
for (const [w, h] of [[1920,1080], [1280,720], [800,600], [2560,1600]]) {
  const point = layout.position(saved.screens["eDP-1"].weather, 0, 0, 310, 300, w, h)
  assert.ok(point.x >= 12 && point.x + 310 <= w - 12)
  assert.ok(point.y >= 46 && point.y + 300 <= h - 12)
  const ratio = layout.fraction(point.x, point.y, 310, 300, w, h)
  const again = layout.position(ratio, 0, 0, 310, 300, w, h)
  assert.ok(Math.abs(again.x - point.x) <= 4.1)
  assert.ok(Math.abs(again.y - point.y) <= 4.1)
}
assert.equal(layout.month(new Date(2024, 1, 29, 12)).filter(v => v.day).length, 29)
assert.equal(layout.month(new Date(2026, 1, 20, 12)).filter(v => v.day).length, 28)
assert.equal(layout.month(new Date(2026, 8, 20, 12)).find(v => v.today).day, 20)
console.log("widget layout: persistence, isolation, bounds, snapping, calendar ok")
